Letgo.WebUI/Controllers/API_AdvertController.cs
using AutoMapper;
using Letgo.BusinessLayer.API.Abstract;
using Letgo.BusinessLayer.Db.Abstract;
using Letgo.BusinessLayer.Db.Concrete;
using Letgo.Entities.Concrete;
using Letgo.WebUI.DTO_s;
using Letgo.WebUI.Models;
using Letgo.WebUI.Models.DTO_s;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Extensions.Hosting;
using NuGet.Protocol.Plugins;
using System;
using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;

namespace Letgo.WebUI.Controllers
{
    public class API_AdvertController : Controller
    {
        private readonly IAdvertManager advertManager;
        private readonly IAdvertStatusManager statusManager;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly IAdvertManagerDb advertManagerDb;
        private readonly IhierarchicalCategoriesManagerDb categoryManagerDb;
        private readonly IAdvertStatusManagerDb statusManagerDb;
        private readonly UserManager<User> userManager;
        private readonly IChatManagerDb chatManager;

        public API_AdvertController
            (
            IAdvertManager advertManager,
            IAdvertStatusManager statusManager,
            IMapper mapper,
            IWebHostEnvironment hostEnvironment,
            IAdvertManagerDb advertManagerDb,
            IhierarchicalCategoriesManagerDb categoryManagerDb,
            IAdvertStatusManagerDb statusManagerDb,
            UserManager<User> userManager,
            IChatManagerDb chatManager
            )
        {
            this.advertManager = advertManager;
            this.statusManager = statusManager;
            this.mapper = mapper;
            this.hostEnvironment = hostEnvironment;
            this.advertManagerDb = advertManagerDb;
            this.categoryManagerDb = categoryManagerDb;
            this.statusManagerDb = statusManagerDb;
            this.userManager = userManager;
            this.chatManager = chatManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("/admin/ilanolustur/{ObjectID}")]
        public IActionResult GetCreate(string ObjectID)
        {
            var advert = advertManagerDb.GetById(ObjectID).Result;
            advert.Categories = categoryManagerDb.GetAll(c => c.AdvertObjectID == advert.ObjectID).Result.FirstOrDefault();
            return View(advert);
        }

        [HttpPost]
        public IActionResult PostCreate(Advert advert)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(advert);
            }
            try
            {
                advertManager.CreateAsync("adverts", advert);
                var status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                status.IsOnAir = true;
                status.IsSold = false;
                status.IsRemove = false;
                status.IsApproved = false;
                status.IsDenied = false;
                status.IsModify = false;
                statusManagerDb.Update(status);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(advert);
            }
        }
        [HttpGet]
        [Route("/admin/guncelle/{ObjectID}")]
        public IActionResult GetUpdate(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                var newAdvert = mapper.Map<Advert>(advert.Result);
                return View(newAdvert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostUpdate(AdvertUpdateDTO dTO)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(dTO);
            }
            try
            {
                var advert = mapper.Map<Advert>(dTO);
                advertManager.UpdateAsync("adverts", advert);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(dTO);
            }
        }
        [HttpGet]
        [Route("/admin/ilansil/{ObjectID}")]
        public IActionResult GetDelete(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostDelete(string ObjectID)
        {
            try
            {
                advertManager.DeleteAsync("adverts", ObjectID);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [AllowAnonymous]
        [HttpGet]        
        [Route("/detay/{ObjectID}")]
        public async Task<IActionResult> GetDetail(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                var chats = await chatManager.GetAll(c => c.AdvertObjectID == advert.Result.ObjectID);

                foreach (var chat in chats)
                {
                    if (chat.AdvertObjectID != advert.Result.ObjectID && chat.SenderId != await getUserId() && chat.ReceiverId != advert.Result.SellerId)
                    {
                        Chat chatModel = new()
                        {
                            AdvertObjectID = advert.Result.ObjectID,
                            SenderId = await getUserId(),
                            ReceiverId = advert.Result.SellerId
                        };
                        await chatManager.Create(chatModel);
                    }
                }

                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }

        public async Task<string> getUserId()
        {
            var user = await userManager.GetUserAsync(User);
            return user.Id;
        }
    }
}

Letgo.WebUI/Controllers/DB_AdvertController.cs
using AutoMapper;
using Letgo.BusinessLayer.API.Abstract;
using Letgo.BusinessLayer.Db.Abstract;
using Letgo.BusinessLayer.Db.Concrete;
using Letgo.Entities.Concrete;
using Letgo.WebUI.DTO_s;
using Letgo.WebUI.Models.DTO_s;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Letgo.WebUI.Controllers
{
    public class DB_AdvertController : Controller
    {
        private readonly IAdvertManagerDb advertManagerDb;
        private readonly IAdvertStatusManagerDb statusManagerDb;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly IhierarchicalCategoriesManagerDb categoryManagerDb;
        private readonly IAdvertManager advertManagerApi;
        private readonly UserManager<User> userManager;

        public DB_AdvertController
            (
            IAdvertManagerDb advertManager,
            IAdvertStatusManagerDb statusManager,
            IMapper mapper,
            IWebHostEnvironment hostEnvironment,
            IhierarchicalCategoriesManagerDb categoryManager,
            IAdvertManager advertManagerApi,
            UserManager<User> userManager
            )
        {
            this.advertManagerDb = advertManager;
            this.statusManagerDb = statusManager;
            this.mapper = mapper;
            this.hostEnvironment = hostEnvironment;
            this.categoryManagerDb = categoryManager;
            this.advertManagerApi = advertManagerApi;
            this.userManager = userManager;
        }
        [Authorize(Roles = "Admin, Manager")]
        [Route("/dashboard")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/ilanlarim")]
        public IActionResult MyAdverts()
        {
            return View();
        }

        [HttpGet]
        [Route("/ilanolustur")]
        public IActionResult GetCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostCreate(AdvertCreateDTO dTO)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(dTO);
            }
            try
            {
                string photoPath = "";
                if (Request.Form.Files.Count > 0)
                {
                    string uniqueFileName = Guid.NewGuid().ToString() + Path.GetExtension(Request.Form.Files[0].FileName);

                    string path = Path.Combine(hostEnvironment.WebRootPath, "upload_image", uniqueFileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        Request.Form.Files[0].CopyTo(stream);
                    }

                    // Dosyanın yeni yolu
                    photoPath = "/upload_image/" + uniqueFileName;
                }
                else
                {
                    photoPath = "/upload_image/No_image_available.png";
                }

                var advert = mapper.Map<Advert>(dTO);
                advert.Image = photoPath;
                await advertManagerDb.Create(advert);

                AdvertStatus advertStatusModel = new();
                advertStatusModel.AdvertObjectID = advert.ObjectID;
                await statusManagerDb.Create(advertStatusModel);

                hierarchicalCategories categories = new()
                {
                    Lvl0 = dTO.Categories.Lvl0,
                    Lvl1 = dTO.Categories.Lvl1,
                    Lvl2 = dTO.Categories.Lvl2,
                    AdvertObjectID = advert.ObjectID
                };
                categoryManagerDb.Create(categories);

                advert.CategoriesObjectID = categories.ObjectID;
                advert.StatusObjectID = advertStatusModel.ObjectID;
                await advertManagerDb.Update(advert);

                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(dTO);
            }
        }
        [HttpGet]
        [Route("/guncelle/{ObjectID}")]
        public IActionResult GetUpdate(string ObjectID)
        {
            try
            {
                var advert = advertManagerDb.GetById(ObjectID).Result;
                var category = categoryManagerDb.GetAll(c => c.AdvertObjectID == advert.ObjectID).Result.FirstOrDefault();
                advert.Categories = category;
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public async Task<IActionResult> PostUpdate(Advert advert)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(advert);
            }
            try
            {
                advert.Categories = categoryManagerDb.GetAll(c => c.AdvertObjectID == advert.ObjectID).Result.FirstOrDefault();
                advert.Status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                advert.Status.IsOnAir = false;
                advert.Status.IsSold = false;
                advert.Status.IsRemove = false;
                advert.Status.IsApproved = false;
                advert.Status.IsDenied = false;
                advert.Status.IsModify = false;
                await advertManagerDb.Update(advert);
                await advertManagerApi.DeleteAsync("adverts", advert.ObjectID);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(advert);
            }
        }
        [HttpGet]
        [Route("/ilansil/{ObjectID}")]
        public IActionResult GetDelete(string ObjectID)
        {
            try
            {
                var advert = advertManagerDb.GetById(ObjectID).Result;
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostDelete(string ObjectID)
        {
            try
            {
                var advert = advertManagerDb.GetById(ObjectID).Result;
                var status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                status.IsOnAir = false;
                status.IsSold = false;
                status.IsRemove = true;
                status.IsApproved = false;
                status.IsDenied = false;
                status.IsModify = false;
                statusManagerDb.Update(status);
                advertManagerApi.DeleteAsync("adverts", advert.ObjectID);

                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpGet]
        [Route("/admin/detay/{ObjectID}")]
        public async Task<IActionResult> GetDetail(string ObjectID)
        {
            try
            {
                var advert = advertManagerDb.GetById(ObjectID).Result;
                var status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                var user = await userManager.GetUserAsync(User);
                if (status.IsOnAir != true && user.Id != advert.SellerId)
                {
                    return Redirect("/Identity/Account/AccessDenied");
                }
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdvertDenied(string ObjectID)
        {
            try
            {
                var advertStatus = statusManagerDb.GetById(ObjectID).Result;
                advertStatus.IsOnAir = false;
                advertStatus.IsSold = true;
                advertStatus.IsRemove = false;
                advertStatus.IsApproved = false;
                advertStatus.IsDenied = true;
                advertStatus.IsModify = false;
                await statusManagerDb.Update(advertStatus);
                return Redirect("~/dashboard");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/dashboard");
            }
        }
        [HttpPost]
        public async Task<IActionResult> IsSold(string ObjectID)
        {
            try
            {
                advertManagerApi.DeleteAsync("adverts", ObjectID);
                var advert = advertManagerDb.GetById(ObjectID).Result;
                var status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                status.IsOnAir = false;
                status.IsSold = true;
                status.IsRemove = false;
                status.IsApproved = false;
                status.IsDenied = false;
                status.IsModify = false;
                await statusManagerDb.Update(status);
                return Redirect("~/");
            }
            catch (Exception ex)
            {

Letgo.WebUI/Views/DB_Advert/GetCreate.cshtml
@using Letgo.WebUI.Models.DTO_s;
@using Microsoft.AspNetCore.Identity;
@model AdvertCreateDTO
@inject UserManager<User> userManager;
@{
    var user = await userManager.GetUserAsync(User);
}

@*<input type="hidden" value="@Model.Result.Image" asp-for="@Model.Result.Image" />
        <input type="hidden" value="@Model.Result.AdvertStatusId" asp-for="@Model.Result.AdvertStatusId" />
        <input type="hidden" value="@Model.Result.hierarchicalCategories" asp-for="@Model.Result.hierarchicalCategories" />
        <input type="hidden" value="@Model.Result.ObjectID" asp-for="@Model.Result.ObjectID" />
        <input type="hidden" value="@Model.Result.SellerId" asp-for="@Model.Result.SellerId" />
        <input type="hidden" value="@Model.Result.Slug" asp-for="@Model.Result.Slug" />
        <input type="hidden" value="@Model.Result.UpdateDate" asp-for="@Model.Result.UpdateDate" />
        <input type="hidden" value="@Model.Result.CreationDate" asp-for="@Model.Result.CreationDate" />*@

<form asp-controller="DB_Advert" asp-action="PostCreate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" value="@user.Id" asp-for="@Model.SellerId" />
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl0">Kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl0" required />
            <span asp-validation-for="@Model.Categories.Lvl0" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl1">Alt kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl1" required />
            <span asp-validation-for="@Model.Categories.Lvl1" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl2">Marka adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl2" required />
            <span asp-validation-for="@Model.Categories.Lvl2" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Image">Fotoğraf</label>
            <input class="form-control" asp-for="@Model.Image" type="file" accept="image/*">
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">İlan Adı</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">Açıklaması</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Fiyatı</label>
            <input class="form-control" type="text" asp-for="@Model.Price" required />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>

Letgo.WebUI/Views/DB_Advert/GetDelete.cshtml
@model Advert

@*<input type="hidden" value="@Model.Result.Image" asp-for="@Model.Result.Image" />
        <input type="hidden" value="@Model.Result.AdvertStatusId" asp-for="@Model.Result.AdvertStatusId" />
        <input type="hidden" value="@Model.Result.hierarchicalCategories" asp-for="@Model.Result.hierarchicalCategories" />
        <input type="hidden" value="@Model.Result.ObjectID" asp-for="@Model.Result.ObjectID" />
        <input type="hidden" value="@Model.Result.SellerId" asp-for="@Model.Result.SellerId" />
        <input type="hidden" value="@Model.Result.Slug" asp-for="@Model.Result.Slug" />
        <input type="hidden" value="@Model.Result.UpdateDate" asp-for="@Model.Result.UpdateDate" />
        <input type="hidden" value="@Model.Result.CreationDate" asp-for="@Model.Result.CreationDate" />*@

<!-- Modal -->
<div class="modal fade" id="deleteAdvertDbModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="deleteAdvertDbModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteAdvertDbModallLabel">İlanı Sil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="DB_Advert" asp-action="PostDelete" asp-route-ObjectID="@Model.ObjectID" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="modal-body" id="modalContent">
                    <div class="mb-3">
                        <label>İlanı yayından kaldırmak istediğinize emin misiniz?</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-danger">Evet</button>
                </div>
            </form>
        </div>
    </div>
</div>

Letgo.WebUI/Views/DB_Advert/GetDetail.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> userManager;
@model Advert

@{
    var user = await userManager.GetUserAsync(User);
}

@if (Model.SellerId == user.Id)
{
    <a class="btn btn-primary" asp-controller="DB_Advert" asp-action="GetUpdate" asp-route-ObjectID="@Model.ObjectID">İlan Guncelle</a>
    <a class="btn btn-danger" id="deleteAdvertDbModalButton" data-bs-toggle="modal" data-bs-target="#deleteAdvertDbModal">
        İlan Sil
    </a>
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Image</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">@Model.ObjectID</th>
            <td>@Model.Name</td>
            <td>@Model.Image</td>
            <td>@Model.Description</td>
            <td>@Model.Price</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    document.getElementById("deleteAdvertDbModalButton").addEventListener("click", function () {
        $("#deleteAdvertDbModal").modal("show");
    });
</script>

<partial name="GetDelete" />

Letgo.WebUI/Views/DB_Advert/GetUpdate.cshtml
@using Letgo.WebUI.DTO_s;
@model Advert

@*<input type="hidden" value="@Model.Image" asp-for="@Model.Image" />
        <input type="hidden" value="@Model.AdvertStatusId" asp-for="@Model.AdvertStatusId" />
        <input type="hidden" value="@Model.hierarchicalCategories" asp-for="@Model.hierarchicalCategories" />
        <input type="hidden" value="@Model.ObjectID" asp-for="@Model.ObjectID" />
        <input type="hidden" value="@Model.SellerId" asp-for="@Model.SellerId" />
        <input type="hidden" value="@Model.Slug" asp-for="@Model.Slug" />
        <input type="hidden" value="@Model.UpdateDate" asp-for="@Model.UpdateDate" />
        <input type="hidden" value="@Model.CreationDate" asp-for="@Model.CreationDate" />*@

<form asp-controller="DB_Advert" asp-action="PostUpdate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" value="@Model.ObjectID" asp-for="@Model.ObjectID" />
        <input type="hidden" value="@Model.UpdateDate" asp-for="@Model.UpdateDate" />
        <input type="hidden" value="@Model.CreationDate" asp-for="@Model.CreationDate" />
        <input type="hidden" value="@Model.Slug" asp-for="@Model.Slug" />
        <input type="hidden" value="@Model.StatusObjectID" asp-for="@Model.StatusObjectID" />
        <input type="hidden" value="@Model.SellerId" asp-for="@Model.SellerId" />
        <input type="hidden" value="@Model.CategoriesObjectID" asp-for="@Model.CategoriesObjectID" />
        <input type="hidden" value="@Model.Image" asp-for="@Model.Image" />
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl0">Kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl0" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl0" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl1">Alt kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl1" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl1" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl2">Marka adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl2" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl2" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Image">Fotoğraf</label>
            <input class="form-control" asp-for="@Model.Image" type="file" multiple accept="image/*">
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">İlan Adı</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">Açıklaması</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Fiyatı</label>
            <input class="form-control" type="text" asp-for="@Model.Price" required />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>

Letgo.WebUI/Views/DB_Advert/Index.cshtml
@inject IAdvertManagerDb advertManager;
@{
    var adverts = advertManager.GetAllInclude(null, a => a.Status).Result;
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">İlan Adı</th>
            <th scope="col">Açıklaması</th>
            <th scope="col">Fiyatı</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var advert in adverts)
        {
            if (
            advert.Status.IsSold == false &&
            advert.Status.IsModify == false &&
            advert.Status.IsOnAir == false &&
            advert.Status.IsApproved == false &&
            advert.Status.IsDenied == false &&
            advert.Status.IsRemove == false
            )
            {
                <tr>
                    <th scope="row">@advert.ObjectID</th>
                    <td>@advert.Name</td>
                    <td>@advert.Description</td>
                    <td>@advert.Price</td>
                    <td>
                        <a class="btn btn-success"
                           asp-controller="API_Advert"
                           asp-action="GetCreate"
                           asp-route-ObjectID="@advert.ObjectID">İlanı Onayla</a>
                        <form asp-controller="DB_Advert" asp-action="AdvertDenied" asp-route-ObjectID="@advert.Status.ObjectID" method="post">
                            <button type="submit" class="btn btn-danger">İlanı Reddet</button>
                        </form>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>