Letgo.WebUI/Controllers/AdvertController.cs
using AutoMapper;
using Letgo.BusinessLayer.Abstract;
using Letgo.Entities.Concrete;
using Letgo.WebUI.DTO_s;
using Letgo.WebUI.Models.DTO_s;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Extensions.Hosting;
using System.Text.RegularExpressions;

namespace Letgo.WebUI.Controllers
{
    public class AdvertController : Controller
    {
        private readonly IAdvertManager advertManager;
        private readonly IAdvertStatusManager statusManager;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostEnvironment;

        public AdvertController
            (
            IAdvertManager advertManager,
            IAdvertStatusManager statusManager,
            IMapper mapper,
            IWebHostEnvironment hostEnvironment
            )
        {
            this.advertManager = advertManager;
            this.statusManager = statusManager;
            this.mapper = mapper;
            this.hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("/ilanolustur")]
        public IActionResult PostCreate()
        {
            return View();
        }

        [HttpPost]
        [Route("/ilanolustur")]
        public IActionResult PostCreate(AdvertCreateDTO dTO)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(dTO);
            }
            try
            {
                string photoPath = "";
                if (Request.Form.Files.Count > 0)
                {
                    foreach (var image in Request.Form.Files)
                    {
                        string path = Path.Combine(hostEnvironment.WebRootPath, "upload_image", image.FileName);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            image.CopyTo(stream);
                        }
                        path = "/upload_image/" + image.FileName;
                        photoPath += path;
                    }
                }
                else
                {
                    photoPath = "/upload_image/No_image_available.png";
                }
                var advert = mapper.Map<Advert>(dTO);
                advert.Image = photoPath;
                advertManager.CreateAsync("adverts", advert);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(dTO);
            }
        }
        [HttpGet]
        [Route("/guncelle/{ObjectID}")]
        public IActionResult GetUpdate(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                AdvertUpdateDTO mappedAdvertModel = new()
                {
                    ObjectID = advert.Result.ObjectID,
                    CreationDate = advert.Result.CreationDate,
                    UpdateDate = advert.Result.UpdateDate,
                    Name = advert.Result.Name,
                    Image = advert.Result.Image,
                    Description = advert.Result.Description,
                    Price = advert.Result.Price,
                    Slug = advert.Result.Slug,
                    StatusId = advert.Result.StatusId,
                    SellerId = advert.Result.SellerId,
                    hierarchicalCategories = advert.Result.hierarchicalCategories
                };
                return View(mappedAdvertModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostUpdate(AdvertUpdateDTO dTO)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(dTO);
            }
            try
            {
                var advert = mapper.Map<Advert>(dTO);
                advertManager.UpdateAsync("adverts", advert);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(dTO);
            }
        }
        [HttpGet]
        [Route("/ilansil/{ObjectID}")]
        public IActionResult GetDelete(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostDelete(string ObjectID)
        {
            try
            {
                advertManager.DeleteAsync("adverts", ObjectID);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpGet]
        [Route("/detay/{ObjectID}")]
        public IActionResult GetDetail(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
    }
}

Letgo.WebUI/Views/Advert/GetDelete.cshtml
@model Task<Advert>

        @*<input type="hidden" value="@Model.Result.Image" asp-for="@Model.Result.Image" />
        <input type="hidden" value="@Model.Result.AdvertStatusId" asp-for="@Model.Result.AdvertStatusId" />
        <input type="hidden" value="@Model.Result.hierarchicalCategories" asp-for="@Model.Result.hierarchicalCategories" />
        <input type="hidden" value="@Model.Result.ObjectID" asp-for="@Model.Result.ObjectID" />
        <input type="hidden" value="@Model.Result.SellerId" asp-for="@Model.Result.SellerId" />
        <input type="hidden" value="@Model.Result.Slug" asp-for="@Model.Result.Slug" />
        <input type="hidden" value="@Model.Result.UpdateDate" asp-for="@Model.Result.UpdateDate" />
        <input type="hidden" value="@Model.Result.CreationDate" asp-for="@Model.Result.CreationDate" />*@

<!-- Modal -->
<div class="modal fade" id="deleteAdvertModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="deleteAdvertModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteAdvertModallLabel">İlanı Sil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="Advert" asp-action="PostDelete" asp-route-ObjectID="@Model.Result.ObjectID" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="modal-body" id="modalContent">
                    <div class="mb-3">
                        <label>İlanı silmek istediğinize emin misiniz?</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-danger">Evet</button>
                </div>
            </form>
        </div>
    </div>
</div>

Letgo.WebUI/Views/Advert/GetDetail.cshtml
@model Task<Advert>

<a class="btn btn-primary" asp-controller="Advert" asp-action="GetUpdate" asp-route-ObjectID="@Model.Result.ObjectID">İlan Guncelle</a>
<a class="btn btn-danger" id="deleteAdvertModalButton" data-bs-toggle="modal" data-bs-target="#deleteAdvertModal">
    İlan Sil
</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Image</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">@Model.Result.ObjectID</th>
            <td>@Model.Result.Name</td>
            <td>@Model.Result.Image</td>
            <td>@Model.Result.Description</td>
            <td>@Model.Result.Price</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    document.getElementById("deleteAdvertModalButton").addEventListener("click", function () {
        $("#deleteAdvertModal").modal("show");
    });
</script>

<partial name="GetDelete" />

Letgo.WebUI/Views/Advert/GetUpdate.cshtml
@using Letgo.WebUI.DTO_s;
@model AdvertUpdateDTO

<form asp-controller="Advert" asp-action="PostUpdate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" value="@Model.StatusId" asp-for="@Model.StatusId" />
        <input type="hidden" value="@Model.Slug" asp-for="@Model.Slug" />
        <input type="hidden" value="@Model.UpdateDate" asp-for="@Model.UpdateDate" />
        <input type="hidden" value="@Model.CreationDate" asp-for="@Model.CreationDate" />
        <input type="hidden" value="@Model.ObjectID" asp-for="@Model.ObjectID" />
        <input type="hidden" value="@Model.SellerId" asp-for="@Model.SellerId" />
        <div class="mb-3">
            <label asp-for="@Model.hierarchicalCategories.Lvl0">Kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.hierarchicalCategories.Lvl0" required disabled/>
            <span asp-validation-for="@Model.hierarchicalCategories.Lvl0" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.hierarchicalCategories.Lvl1">Alt kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.hierarchicalCategories.Lvl1" required disabled />
            <span asp-validation-for="@Model.hierarchicalCategories.Lvl1" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.hierarchicalCategories.Lvl2">Marka adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.hierarchicalCategories.Lvl2" required disabled />
            <span asp-validation-for="@Model.hierarchicalCategories.Lvl2" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Image">Photo</label>
            <input class="form-control" asp-for="@Model.Image" type="file" multiple accept="image/*">
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">Name</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">Description</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Price</label>
            <input class="form-control" type="text" asp-for="@Model.Price" required />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>

Letgo.WebUI/Views/Advert/PostCreate.cshtml
@using Letgo.WebUI.Models.DTO_s;
@model AdvertCreateDTO

<form asp-controller="Advert" asp-action="PostCreate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <div class="mb-3">
            <label asp-for="@Model.Image">Photo</label>
            <input class="form-control" asp-for="@Model.Image" type="file" multiple accept="image/*">
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">Name</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">Description</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Price</label>
            <input class="form-control" type="text" asp-for="@Model.Price" required/>
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>