Letgo.WebUI/Controllers/API_AdvertController.cs
using AutoMapper;
using Letgo.BusinessLayer.API.Abstract;
using Letgo.BusinessLayer.Db.Abstract;
using Letgo.BusinessLayer.Db.Concrete;
using Letgo.Entities.Concrete;
using Letgo.WebUI.DTO_s;
using Letgo.WebUI.Models;
using Letgo.WebUI.Models.DTO_s;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Extensions.Hosting;
using NuGet.Protocol.Plugins;
using System;
using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;

namespace Letgo.WebUI.Controllers
{
    public class API_AdvertController : Controller
    {
        private readonly IAdvertManager advertManager;
        private readonly IAdvertStatusManager statusManager;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly IAdvertManagerDb advertManagerDb;
        private readonly IhierarchicalCategoriesManagerDb categoryManagerDb;
        private readonly IAdvertStatusManagerDb statusManagerDb;
        private readonly UserManager<User> userManager;
        private readonly IChatManagerDb chatManager;

        public API_AdvertController
            (
            IAdvertManager advertManager,
            IAdvertStatusManager statusManager,
            IMapper mapper,
            IWebHostEnvironment hostEnvironment,
            IAdvertManagerDb advertManagerDb,
            IhierarchicalCategoriesManagerDb categoryManagerDb,
            IAdvertStatusManagerDb statusManagerDb,
            UserManager<User> userManager,
            IChatManagerDb chatManager
            )
        {
            this.advertManager = advertManager;
            this.statusManager = statusManager;
            this.mapper = mapper;
            this.hostEnvironment = hostEnvironment;
            this.advertManagerDb = advertManagerDb;
            this.categoryManagerDb = categoryManagerDb;
            this.statusManagerDb = statusManagerDb;
            this.userManager = userManager;
            this.chatManager = chatManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("/admin/ilanolustur/{ObjectID}")]
        public IActionResult GetCreate(string ObjectID)
        {
            var advert = advertManagerDb.GetById(ObjectID).Result;
            advert.Categories = categoryManagerDb.GetAll(c => c.AdvertObjectID == advert.ObjectID).Result.FirstOrDefault();
            return View(advert);
        }

        [HttpPost]
        public IActionResult PostCreate(Advert advert)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(advert);
            }
            try
            {
                advertManager.CreateAsync("adverts", advert);
                var status = statusManagerDb.GetById(advert.StatusObjectID).Result;
                status.IsOnAir = true;
                status.IsSold = false;
                status.IsRemove = false;
                status.IsApproved = false;
                status.IsDenied = false;
                status.IsModify = false;
                statusManagerDb.Update(status);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(advert);
            }
        }
        [HttpGet]
        [Route("/admin/guncelle/{ObjectID}")]
        public IActionResult GetUpdate(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                var newAdvert = mapper.Map<Advert>(advert.Result);
                return View(newAdvert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostUpdate(AdvertUpdateDTO dTO)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Fill in the mandatory fields!");
                return View(dTO);
            }
            try
            {
                var advert = mapper.Map<Advert>(dTO);
                advertManager.UpdateAsync("adverts", advert);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return View(dTO);
            }
        }
        [HttpGet]
        [Route("/admin/ilansil/{ObjectID}")]
        public IActionResult GetDelete(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public IActionResult PostDelete(string ObjectID)
        {
            try
            {
                advertManager.DeleteAsync("adverts", ObjectID);
                return Redirect("~/");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [AllowAnonymous]
        [HttpGet]        
        [Route("/detay/{ObjectID}")]
        public async Task<IActionResult> GetDetail(string ObjectID)
        {
            try
            {
                var advert = advertManager.GetByIdAsync("adverts", ObjectID);
                var chats = await chatManager.GetAll(c => c.AdvertObjectID == advert.Result.ObjectID);

                foreach (var chat in chats)
                {
                    if (chat.AdvertObjectID != advert.Result.ObjectID && chat.SenderId != await getUserId() && chat.ReceiverId != advert.Result.SellerId)
                    {
                        Chat chatModel = new()
                        {
                            AdvertObjectID = advert.Result.ObjectID,
                            SenderId = await getUserId(),
                            ReceiverId = advert.Result.SellerId
                        };
                        await chatManager.Create(chatModel);
                    }
                }

                return View(advert);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }

        public async Task<string> getUserId()
        {
            var user = await userManager.GetUserAsync(User);
            return user.Id;
        }
    }
}

Letgo.WebUI/Controllers/ChatController.cs
using Letgo.BusinessLayer.API.Concrete;
using Letgo.BusinessLayer.Db.Abstract;
using Letgo.BusinessLayer.Db.Concrete;
using Letgo.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Letgo.WebUI.Controllers
{
    [Authorize(Roles = "Member, Admin, Manager")]
    public class ChatController : Controller
    {
        private readonly IChatManagerDb chatManager;
        private readonly IChatHistoryManagerDb chatHistoryManager;
        private readonly UserManager<User> userManager;
        public ChatController(IChatManagerDb chatManager, IChatHistoryManagerDb chatHistoryManager, UserManager<User> userManager)
        {
            this.chatManager = chatManager;
            this.chatHistoryManager = chatHistoryManager;
            this.userManager = userManager;
        }

        public string getUserId()
        {
            var user = userManager.GetUserAsync(User).Result;
            return user.Id;
        }

        [Route("/mesajlarim")]
        public async Task<IActionResult> Chats()
        {
            try
            {
                var chats = await chatManager.GetAll(c => c.ReceiverId == getUserId() || c.SenderId == getUserId());
                return View(chats);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }

        [Route("/mesajlarim/detay/{ObjectID}")]
        public async Task<IActionResult> GetDetail(string ObjectID)
        {
            try
            {
                var chatDetails = await chatHistoryManager.GetAll(ch => ch.ChatObjectID == ObjectID);
                var chat = await chatManager.GetById(ObjectID);
                if (chat.SenderId == getUserId() || chat.ReceiverId == getUserId())
                {
                    return View(chat);
                }
                else
                {
                    return Redirect("/Identity/Account/AccessDenied");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
            
        }
        [HttpPost]
        public async Task<IActionResult> SendMessage([FromBody] ChatHistory chatHistory)
        {
            try
            {
                await chatHistoryManager.Create(chatHistory);
                return Redirect("~/mesajlarim/detay/" + chatHistory.ChatObjectID);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
        [HttpPost]
        public async Task<IActionResult> CreateChat(string AdvertObjectID, string SenderId, string ReceiverId)
        {
            try
            {
                Chat chat = new()
                {
                    AdvertObjectID = AdvertObjectID,
                    SenderId = SenderId,
                    ReceiverId = ReceiverId
                };
                await chatManager.Create(chat);
                return Redirect("~/mesajlarim/detay/" + chat.ObjectID);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error was encountered.\nError message: {ex.Message}");
                return Redirect("~/");
            }
        }
    }
}

Letgo.WebUI/Views/API_Advert/GetCreate.cshtml
@using Letgo.WebUI.Models.DTO_s;
@using Microsoft.AspNetCore.Identity;
@model Advert
@inject UserManager<User> userManager;
@{
    var user = await userManager.GetUserAsync(User);
}

<form asp-controller="API_Advert" asp-action="PostCreate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" value="@Model.ObjectID" asp-for="@Model.ObjectID" />
        <input type="hidden" value="@Model.UpdateDate" asp-for="@Model.UpdateDate" />
        <input type="hidden" value="@Model.CreationDate" asp-for="@Model.CreationDate" />
        <input type="hidden" value="@Model.Slug" asp-for="@Model.Slug" />
        <input type="hidden" value="@Model.StatusObjectID" asp-for="@Model.StatusObjectID" />
        <input type="hidden" value="@Model.SellerId" asp-for="@Model.SellerId" />
        <input type="hidden" value="@Model.CategoriesObjectID" asp-for="@Model.CategoriesObjectID" />
        <input type="hidden" value="@Model.Image" asp-for="@Model.Image" />
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl0">Kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl0" required />
            <span asp-validation-for="@Model.Categories.Lvl0" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl1">Alt kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl1" required />
            <span asp-validation-for="@Model.Categories.Lvl1" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl2">Marka adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl2" required />
            <span asp-validation-for="@Model.Categories.Lvl2" class="text-danger"></span>
        </div>
        <div class="mb-3 d-flex flex-column">
            @{var imagesPath = Model.Image.Split(";");}
            <label asp-for="@Model.Image">Photo</label>
            <div class="d-flex">
            @foreach (var image in imagesPath)
            {
                <img src="../../@image" style="width: 10%"/>
            }
            </div>
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">İlan Adı</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">İlan Açıklaması</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Fiyat</label>
            <input class="form-control" type="number" asp-for="@Model.Price" required />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>

Letgo.WebUI/Views/API_Advert/GetDelete.cshtml
@model Task<Advert>

        @*<input type="hidden" value="@Model.Result.Image" asp-for="@Model.Result.Image" />
        <input type="hidden" value="@Model.Result.AdvertStatusId" asp-for="@Model.Result.AdvertStatusId" />
        <input type="hidden" value="@Model.Result.hierarchicalCategories" asp-for="@Model.Result.hierarchicalCategories" />
        <input type="hidden" value="@Model.Result.ObjectID" asp-for="@Model.Result.ObjectID" />
        <input type="hidden" value="@Model.Result.SellerId" asp-for="@Model.Result.SellerId" />
        <input type="hidden" value="@Model.Result.Slug" asp-for="@Model.Result.Slug" />
        <input type="hidden" value="@Model.Result.UpdateDate" asp-for="@Model.Result.UpdateDate" />
        <input type="hidden" value="@Model.Result.CreationDate" asp-for="@Model.Result.CreationDate" />*@

<!-- Modal -->
<div class="modal fade" id="deleteAdvertModal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="deleteAdvertModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteAdvertModallLabel">İlanı Sil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="DB_Advert" asp-action="PostDelete" asp-route-ObjectID="@Model.Result.ObjectID" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="modal-body" id="modalContent">
                    <div class="mb-3">
                        <label>İlanı silmek istediğinize emin misiniz?</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-danger">Evet</button>
                </div>
            </form>
        </div>
    </div>
</div>

Letgo.WebUI/Views/API_Advert/GetDetail.cshtml
@using Microsoft.AspNetCore.Identity;
@model Task<Advert>
@inject UserManager<User> userManager;
@inject SignInManager<User> signManager;
@inject IChatManagerDb chatManager;
@{

}
@if (signManager.IsSignedIn(User))
{
    var user = await userManager.GetUserAsync(User);
    var chats = await chatManager.GetAll(c => c.AdvertObjectID == Model.Result.ObjectID);
    @if (Model.Result.SellerId == user.Id)
    {
        <div class="d-flex justify-content-center align-items-center">
            <a class="btn btn-primary" asp-controller="DB_Advert" asp-action="GetUpdate" asp-route-ObjectID="@Model.Result.ObjectID">İlan Guncelle</a>
            <a class="btn btn-danger" id="deleteAdvertModalButton" data-bs-toggle="modal" data-bs-target="#deleteAdvertModal">Yayından Kaldır</a>
            <form asp-controller="DB_Advert" asp-action="IsSold" asp-route-ObjectID="@Model.Result.ObjectID" method="post">
                <button class="btn btn-primary" type="submit">Satıldı Olarak İşaretle</button>
            </form>
        </div>
    }

    @if (User.Identity.IsAuthenticated && user.Id != Model.Result.SellerId)
    {
        foreach (var chat in chats)
        {
            if (chat.AdvertObjectID == Model.Result.ObjectID && chat.SenderId == user.Id && chat.ReceiverId == Model.Result.SellerId)
            {
                <a class="btn btn-primary" asp-controller="Chat" asp-action="GetDetail" asp-route-ObjectID="@chat.ObjectID">Mesaj Gönder</a>
            }
        }
    }
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">İlan Adı</th>
            <th scope="col">Fotoğrafı</th>
            <th scope="col">Açıklaması</th>
            <th scope="col">Fiyat</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">@Model.Result.ObjectID</th>
            <td>@Model.Result.Name</td>
            <td>@Model.Result.Image</td>
            <td>@Model.Result.Description</td>
            <td>@Model.Result.Price</td>
        </tr>
    </tbody>
</table>

@if (signManager.IsSignedIn(User))
{
    var user = await userManager.GetUserAsync(User);
    var chats = await chatManager.GetAll(c => c.AdvertObjectID == Model.Result.ObjectID);
    @section Scripts{

    @if (Model.Result.SellerId == user.Id)
        {
            <script>
                document.getElementById("deleteAdvertModalButton").addEventListener("click", function () {
                    $("#deleteAdvertModal").modal("show");
                });
            </script>
        }

        @if (User.Identity.IsAuthenticated && user.Id != Model.Result.SellerId)
        {
            <script>
                document.getElementById('sendMessageButton').addEventListener('click', function () {
                    var advertObjectId = "@Html.Raw(Model.Result.ObjectID)";
                    var senderId = "@Html.Raw(user.Id)";
                    var reveiverId = "@Html.Raw(Model.Result.SellerId)";
                    $.ajax({
                        url: '/Chat/CreateChat',
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({ AdvertObjectID: advertObjectId, SenderId: senderId, ReceiverId: reveiverId }),
                        success: function (result) {
                            console.log(JSON.stringify({ AdvertObjectID: advertObjectId, SenderId: senderId, ReceiverId: reveiverId }));
                        },
                        error: function (error) {
                            console.error('Hata:', error);
                        }
                    });
                });
            </script>
        }
}
}

<partial name="GetDelete" />

Letgo.WebUI/Views/API_Advert/GetUpdate.cshtml
@using Letgo.WebUI.DTO_s;
@model AdvertUpdateDTO

<form asp-controller="DB_Advert" asp-action="PostUpdate" method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl0">Kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl0" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl0" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl1">Alt kategori adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl1" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl1" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Categories.Lvl2">Marka adı yazın</label>
            <input class="form-control" type="text" asp-for="@Model.Categories.Lvl2" required disabled />
            <span asp-validation-for="@Model.Categories.Lvl2" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Image">Fotoğraf</label>
            <input class="form-control" asp-for="@Model.Image" type="file" multiple accept="image/*">
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name">İlan Adı</label>
            <input class="form-control" type="text" asp-for="@Model.Name" required />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description">Açıklaması</label>
            <input class="form-control" type="text" asp-for="@Model.Description" />
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Price">Fiyatı</label>
            <input class="form-control" type="text" asp-for="@Model.Price" required />
            <span asp-validation-for="@Model.Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-success w-100" type="submit">Gönder</button>
        </div>
    </div>
</form>